config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :sinfest, only: :index

  # You can have the root of your site routed with "root"
  root 'welcome#index'
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  enum channel_type: [ :sinfest ]

  has_many :channel_items
  has_one :channel_image
end

app/models/channel_image.rb
class ChannelImage < ActiveRecord::Base
  belongs_to :channel
end

app/models/channel_item.rb
class ChannelItem < ActiveRecord::Base
  belongs_to :channel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sinfest_controller.rb
require 'curb'

class SinfestController < ApplicationController
  EXPIRE_AFTER = 24.hours
  ITEMS_TO_FETCH = 7
  FIRST_COMIC_DATE = '2000-01-17'.to_date
  def index
    @channel = Channel.find_by_channel_type(Channel.channel_types[:sinfest])
    if (@channel.last_build_date < Time.now - EXPIRE_AFTER) then
      update_sinfest
    end
    render formats: :xml
  end

  def update_sinfest
    start_date = ITEMS_TO_FETCH.days.ago
    if(start_date < FIRST_COMIC_DATE) then
      start_date = FIRST_COMIC_DATE
    end

    date = start_date
    today = Time.now.to_date
    ActiveRecord::Base.transaction do
      @channel.channel_items.destroy_all

      while date.to_date <= today do
        pubdate = date.to_date.to_s

        link = "http://www.sinfest.net/view.php?date=#{pubdate}"

        c = Curl::Easy.new(link) do |curl|
          curl.headers['User-Agent'] = 'rss-generator-1.0'
        end
        c.perform

        if(c.status.include? '200') then
          html_doc = Nokogiri::HTML(c.body)
          title = html_doc.xpath('/html/body/div/table[4]/tr[1]/td/table/tbody/tr[1]/td').text
          description = html_doc.xpath('/html/body/div/table[4]/tr[1]/td/table/tbody/tr[2]/td').children.to_s
          description.gsub!(/btphp/, 'http://www.sinfest.net/btphp')
          description.gsub!(/alt/, 'border="0" alt')
          guid = "sinfest-imgs-#{pubdate}"
          ChannelItem.create(link: link, pubdate: pubdate, title: title, description: description, channel: @channel, guid: guid)
        end

        date += 1.day
      end

      @channel.last_build_date = Time.now
      @channel.save
      @channel.reload
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sinfest_helper.rb
module SinfestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_rss.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by rss-generator -->
<rss version="0.92">
        <channel>
                <title><%=channel.title%></title>
                <link><%=channel.link%></link>
                <description><%=channel.description%></description>
                <lastBuildDate><%=channel.last_build_date%></lastBuildDate>
                <copyright></copyright>
                <%- if channel.channel_image.present? %>
                <image>
                        <title><%=channel.channel_image.title%></title>
                        <url><%=channel.channel_image.url%></url>
                        <link><%=channel.channel_image.link%></link>
                        <width><%=channel.channel_image.width%></width>
                        <height><%=channel.channel_image.height%></height>
                </image>
                <% end -%>
                <% channel.channel_items.each do |item| %>
                <item>
                    <title><%= item.title %></title>
                    <link><%= item.link %></link>
                    <guid><%= item.guid %></guid>
                    <pubDate><%= item.pubdate %></pubDate>
                    <description><%= item.description %></description>
                </item>
                <% end %>
        </channel>
</rss>

app/views/sinfest/index.xml.erb
<%= render partial: "shared/rss", locals: {channel: @channel} %>

app/views/welcome/index.html.erb
<h1>RSS Generator</h1>
<p>Right now, we have feeds available for:</p>
<ul>
    <li><%=link_to "Sinfest (http://www.sinfest.net)", sinfest_index_path%></li>
</ul>